### ISSUE TITLE
Non js file example

### ISSUE THREAD

**Issue by bmitchinson** [jesperorb/json-server-heroku#10]
Aside from a piece of middleware I need for my use case, here's an example I've created of deploying to Heroku using only .json files.

Also, the zeit related deployment steps need to be now removed.

https://github.com/bmitchinson/reusable-percl-endpoints

**Comment by jesperorb** [comment]
What is the issue? What's the cons with running it trough a `.js`-file?

> Also, the zeit related deployment steps need to be now removed.

You can open a PR to remove them or change them. I am not up to date with what has happened with `now` since i wrote this repos readme a few years ago.
