### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Mxdi** [jesperorb/json-server-heroku#8]
How exactly do you make a request to the app though once its deployed? What would the url be since its no longer local host?

**Comment by haeke** [comment]
Hello Mxdi,

All you need to do is set the URL that you were using to access the local database i.e. localhost:3000 to the heroku url ( https://[theprojectname].heroku.com/[your endpoint] ) that you created after deploying your project. 

In theory, if you deployed the json-server to heroku correctly, you should be able to access the data from your browser just by visiting the server / URL like ( https://[theprojectname].heroku.com/[your endpoint]). I hope this helps.

**Comment by Mxdi** [comment]
Thanks for the response, I figured this out the same day I opened the ticket. Sorry for being dense. Appreciate the reply.

Sent from Mail for Windows 10
