### ISSUE TITLE
Deploy to Netlify?

### ISSUE THREAD

**Issue by webdevsuperfast** [jesperorb/json-server-heroku#9]
Hi @jesperorb,

Awesome work, I was able to deploy it Heroku but my question is can this be deployed to Netlify? I can't seem to get it to work.

Thanks!

**Comment by jesperorb** [comment]
Hi @webdevsuperfast 

_Netlify_ only deploys static websites as I recall (html, css, js). This repo is run on the backend (node) so you need a hosting site that can run node-applications.
